import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { registrationService } from "../services/registrationService";
import "./CompanyRegistration.css";

const slugify = value => (value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export default function CompanyRegistration(){
  const navigate=useNavigate(); const [form,setForm]=useState({company_name:"",slug:"",admin_name:"",admin_email:"",password:"",confirm:""}); const [slugEdited,setSlugEdited]=useState(false); const [available,setAvailable]=useState(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!form.slug){setAvailable(null);return;} const timer=setTimeout(()=>registrationService.availability(form.slug).then(r=>setAvailable(r.available)).catch(()=>setAvailable(null)),400);return()=>clearTimeout(timer)},[form.slug]);
  const change=e=>{const {name,value}=e.target;setForm(p=>({...p,[name]:value,...(name==="company_name"&&!slugEdited?{slug:slugify(value)}:{})}));if(name==="slug")setSlugEdited(true)};
  const submit=async e=>{e.preventDefault();setError("");if(!form.company_name.trim()){setError("Completa el nombre de la empresa.");return}if(!form.admin_name.trim()||!form.admin_email.trim()){setError("Completa los datos del administrador.");return}if(form.password.length<12){setError("La contraseña debe tener al menos 12 caracteres.");return}if(form.password!==form.confirm){setError("Las contraseñas no coinciden.");return}if(available===false){setError("Ese slug ya está ocupado.");return}setSaving(true);try{const data=await registrationService.register(form);navigate(data.login_url)}catch(err){setError(err.message||"No se pudo crear la empresa.")}finally{setSaving(false)}};
  return <main className="registration-page"><Link to="/" className="public-brand">CibercomHR</Link><section className="registration-card"><div><span className="public-eyebrow">Tu espacio de RH</span><h1>Crea la cuenta de tu empresa</h1><p>Obtendrás una dirección exclusiva y un entorno separado para tu equipo.</p></div><form onSubmit={submit}><label>Nombre de la empresa<input name="company_name" value={form.company_name} onChange={change}/></label><label>Dirección de acceso<div className="slug-input"><span>cibercomrh.com/</span><input name="slug" value={form.slug} onChange={change}/></div>{available===true&&<small className="field-ok">Disponible</small>}{available===false&&<small className="field-error">No disponible</small>}</label><label>Nombre del administrador<input name="admin_name" value={form.admin_name} onChange={change}/></label><label>Correo<input type="email" name="admin_email" value={form.admin_email} onChange={change}/></label><div className="registration-grid"><label>Contraseña<input type="password" name="password" value={form.password} onChange={change}/></label><label>Confirmar<input type="password" name="confirm" value={form.confirm} onChange={change}/></label></div>{error&&<div className="registration-error" role="alert">{error}</div>}<button className="registration-submit" disabled={saving}>{saving?"Creando empresa…":"Crear empresa"}</button></form><p className="registration-login">¿Ya tienes acceso? <Link to="/Login">Inicia sesión</Link></p></section></main>;
}
